spring:
  application:
    name: wms
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wms}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
server:
  port: ${WEB_PORT:8085}